name: Release
on:
  push:
    tags:
      - "202*" # any tag. GH releases (containing binaries for download) require tags

jobs:

  prepare:
    runs-on: [ self-hosted, Linux ]
    if: ${{ github.repository_owner == 'rpardini' }}
    outputs:
      tagName: ${{ steps.tagName.outputs.tag }}
    steps:
      - uses: olegtarasov/get-tag@v2.1 # get the tag name from the ref.
        id: tagName
      # This creates an empty release on the tag with just the header.
      - name: Release ${{ matrix.board }}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # only for tags. GitHub requires tags for releases.
        with:
          body: |
            ### Release ${{ steps.tagName.outputs.tag }}

  "A": # short name because GH will expand with the matrix values
    needs: [ prepare ]
    runs-on: [ self-hosted, Linux, 'can-build-target-impish', '${{ matrix.runnerLabel }}', '${{ matrix.runnerLabelKernel }}' ]
    timeout-minutes: 480 # First builds on new machines can take extremely long until caches are primed
    if: ${{ github.repository_owner == 'rpardini' }}
    strategy:
      fail-fast: false # let other jobs try to complete if one fails
      matrix:
        # include syntax allows sparse matrices
        # see # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-new-combinations

        # board: will build rpardini-<board>.conf in userpatches.
        # desc: markdown for description in release notes
        # runnerLabel: goes into runs-on to select preferred builder via label
        # vars: env vars to pass both to scripts and ./compile.sh
        # aa: GH Actions orders the jobs by the first key value. 'aa' should be first. it never is. it is actually quite pointless trying. it's effectively random.

        include:

          - aa: 0866
            board: rock-5b
            desc: rock-5b, cli, legacy (5.10, by @amazingfate), regular CLI
            runnerLabel: can-build-x86-huge
            runnerLabelKernel: can-build-kernels
            vars: "CLOUD_IMAGE=no BRANCH=legacy"

          - aa: 0867
            board: rock-5b
            desc: rock-5b, cli, legacy (5.10, by @amazingfate), cloud image, user-data at /boot
            runnerLabel: can-build-x86-huge
            runnerLabelKernel: can-build-kernels
            vars: "CLOUD_IMAGE=yes BRANCH=legacy"



    steps:

      - name: Checkout this (release) repo into release dir
        uses: actions/checkout@v2
        with:
          path: release

      - name: Preserve previous run caches and cleanup
        run: |
          sudo --preserve-env \
            REGULAR_USER="$(whoami)" \
            RELEASE_OWNER="${{ github.repository_owner }}" \
            RELEASE_OWNER_AND_REPO="${{ github.repository }}" \
            RELEASE_TAG="${{needs.prepare.outputs.tagName}}" \
            GH_FULL_RUN_ID="${{ github.run_id }}_${{github.run_number}}_${{github.run_attempt}}" \
            bash --noprofile --norc -e release/cleanup.sh

      - name: Checkout build repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/armbian-build
          ref: extensions # branch to build from.
          clean: true # true is default. it *will* delete the hosts /dev if mounted inside.
          path: build

      - name: Restore caches
        run: |
          sudo --preserve-env \
            REGULAR_USER="$(whoami)" \
            RELEASE_OWNER="${{ github.repository_owner }}" \
            RELEASE_OWNER_AND_REPO="${{ github.repository }}" \
            RELEASE_TAG="${{needs.prepare.outputs.tagName}}" \
            GH_FULL_RUN_ID="${{ github.run_id }}_${{github.run_number}}_${{github.run_attempt}}" \
            bash --noprofile --norc -e release/restore_cache.sh

      - name: Build board ${{ matrix.board }}
        id: buildBoard
        working-directory: build
        continue-on-error: false # No, break as soon as possible. Logs will be inline.
        run: |
          sudo --preserve-env ${{ matrix.vars }} \
            REGULAR_USER="$(whoami)" \
            RELEASE_OWNER="${{ github.repository_owner }}" \
            RELEASE_OWNER_AND_REPO="${{ github.repository }}" \
            RELEASE_TAG="${{needs.prepare.outputs.tagName}}" \
            bash --noprofile --norc -e ../release/build.sh \
            "${{ matrix.board }}" "${{ matrix.vars }}"

      - name: Compress/Prepare release ${{ matrix.board }}
        id: compress
        working-directory: build/output
        continue-on-error: false  # No, break as soon as possible. Logs will be inline.
        run: |
          sudo --preserve-env ${{ matrix.vars }} \
            MATRIX_DESC="${{ matrix.desc }}" \
            REGULAR_USER="$(whoami)" \
            RELEASE_OWNER="${{ github.repository_owner }}" \
            RELEASE_OWNER_AND_REPO="${{ github.repository }}" \
            RELEASE_TAG="${{needs.prepare.outputs.tagName}}" \
            bash --noprofile --norc -e ../../release/prepare_release.sh \
            "${{ matrix.board }}" "${{ matrix.vars }}"

      - name: Release ${{ matrix.board }}
        id: release
        uses: softprops/action-gh-release@2d72d869af3bf23602f9593a1e3fd739b80ac1eb # which is v0.1.12, concat release bodies. # @v1 is a moving target
        if: startsWith(github.ref, 'refs/tags/') # only for tags. GitHub requires tags for releases.
        with:
          body_path: build/output/release.md # created by prepare_release.sh
          files: |
            build/output/images/*.xz

      - name: Upload logs as artifact ${{ matrix.board }}
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: build/output/images/build.logs.*.xz

      - name: Finish build with status
        run: |
          if [[ "${{ steps.buildBoard.outcome }}" == "failure" ]]; then
            echo "buildBoard failed"
            exit 2
          fi
